"""empty message

Revision ID: 0a197a3b0a14
Revises: fa7b5d4c6046
Create Date: 2020-05-06 19:30:25.761384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a197a3b0a14'
down_revision = 'fa7b5d4c6046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed =False WHERE completed IS NULL')

    op.alter_column('todos','completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
